### ISSUE TITLE
update kisti link

### ISSUE THREAD

**Issue by YoungKwonJo** [cms-kr/hep-tools#14]
https://github.com/cms-kr/hep-tools/blob/master/create-batch#L135

            if self.dest.startswith('/store/'): self.dest = 'root://cms-xrdr.sdfarm.kr:1094///cms/data/xrd/%s' % self.dest
to 
            if self.dest.startswith('/store/'): self.dest = 'root://cms-xrdr.sdfarm.kr:1094///xrd/%s' % self.dest
Please, update it.

**Comment by YoungKwonJo** [comment]
https://github.com/cms-kr/hep-tools/blob/master/create-batch#L166
from
166             for f in open(secondFileList).readlines():
to
166         if secondFileList:
167             for f in open(secondFileList).readlines():

We may need to add the line as 166 in second's.

**Comment by jhgoh** [comment]
Done. closing this issue.
