### ISSUE TITLE
KISTI 통합팜 사용을 위한 Singularity 기능 지원 요청

### ISSUE THREAD

**Issue by geonmo** [cms-kr/hep-tools#78]
- KISTI에서는 여러 실험 커뮤니티들을 지원하기 위해 제공된 HTCondor 클러스터를 하나로 모아서 지원하려고 합니다.
- 현재 클러스터의 WN들은 CentOS7 으로 구축되었습니다. CMSSW가 주로 SL6만을 지원하기 때문에 이는 큰 문제가 될 수 있습니다.
- 해당 문제를 해결하기 위하여 Singularity를 사용해야 할 것으로 보입니다.

요청 기능

1.  Singularity를 지원하기 위해 아래 3줄을 submit.jds 파일에 추가되어야 합니다. SingularityImage와 SingularityBind 옵션 앞에 있는 "+" 기호는 오타나 첨삭 기호가 아닙니다.  반드시 그대로 넣어주셔야 합니다. 위 기능을 옵션으로 On/Off 를 할 수 있도록 요청합니다.
```bash
requirements = HasSingularity == true
+SingularityImage = "/cvmfs/singularity.opensciencegrid.org/opensciencegrid/osgvo-el6:latest"
+SingularityBind = "/cvmfs, /cms, /share"
```
2. 통합 Farm에서는 작업을 던지는 UI서버를 기준으로 유저들의 커뮤니티를 구분할 예정입니다. condor_submit의 alias를 설정하여 해당 명령어 옵션을 추가할 예정이지만, JDS 파일 자체에서도 해당 명령어를 추가하였으면 합니다. 아래 1줄을 추가해주십시오. 다음 명령어는 KISTI라면 언제든 사용해도 무방한 것으로 확인하였습니다.
```bash
accounting_group=group_cms
```

**Comment by jhgoh** [comment]
1,2 구현 해 넣었습니다. 확인 해 주세요.

**Comment by geonmo** [comment]
PR 머지하였습니다. 확인 완료했습니다.
